jaffle-data:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: co24109.us-east-2.aws
      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      role: reporter
      database: analytics
      warehouse: epd_developing
      schema: jaffle_shop_raw
