jaffle-data:
 target: dev
 outputs:
   dev:
     type: snowflake
     account: https://co24109.us-east-2.aws.snowflakecomputing.com
     user: $DBT_ENV_SECRET_USER
     password: $DBT_ENV_SECRET_PASSWORD
     role: reporter
     database: analytics
     warehouse: epd_developing
     schema: jaffle_shop