name: Generate dbt Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Run on pushes to the main branch

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Step 3: Install dbt and dependencies
      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Set up Snowflake profile
        env:
          SNOWFLAKE_USER: ${{ secrets.DBT_ENV_SECRET_USER }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          mkdir -p .dbt/
          echo "snowflake:" >> .dbt/profiles.yml
          echo " target: dev" >> .dbt/profiles.yml
          echo " outputs:" >> .dbt/profiles.yml
          echo "   dev:" >> .dbt/profiles.yml
          echo "     type: snowflake" >> .dbt/profiles.yml
          echo "     account: $SNOWFLAKE_ACCOUNT" >> .dbt/profiles.yml
          echo "     user: $SNOWFLAKE_USER" >> .dbt/profiles.yml
          echo "     password: ${{ secrets.DBT_ENV_SECRET_PASSWORD }}" >> .dbt/profiles.yml
          echo "     role: reporter" >> .dbt/profiles.yml
          echo "     database: analytics" >> .dbt/profiles.yml
          echo "     warehouse: epd_developing" >> .dbt/profiles.yml
          echo "     schema: jaffle_shop" >> .dbt/profiles.yml
      - name: Run dbt Docs Generate
        env:
          DBT_PROJECT_DIR: .
          DBT_PROFILES_DIR: .dbt
        run: |
          dbt docs generate

      # Step 6: Save Artifacts (optional)
      - name: Upload Documentation
        uses: actions/upload-artifact@v3
        with:
          name: dbt-docs
          path: target/
